[WSC-013] 스터디 게시글 마크업 작업
MIC-TEAM/wellseecoding-front pull request #10
Opened 2021-08-22 14:04 UTC by junh0328

## 이슈 번호

#9 

## 📄 이슈 내용
- 재사용 가능한 컴포넌트(components/Common)를 기반으로 마크업
- 피그마 디자인에 사용된 svg 파일을 코드에 적용

## 📝 상세 내용

### 생성한 컴포넌트

- FlatBox (게시글 map 메서드 돌 때, 반복되는 코드 재사용을 위해)
- HashWrap (해시태그 박스 컴포넌트화)
- BackOptional (헤더 부분 커스텀에 실패하여 새로 추가..)
- PostFooter(글쓰기 푸터 부분)

### 특히 피드백 요청 부분

- 전에 현주님께 제가 피드백 드렸던 부분인데, 모바일 미디어 쿼리에서 적용이 밑에 부분이 짤려서 안보이는 부분이 있습니다

https://user-images.githubusercontent.com/54658162/130357968-a495bbb2-dc84-483a-9116-ab93819f3f1e.mov

- 스크롤 관련하여 문제가 있어서, 기존 _app.tsx 에 적용되었던 max-width 관련 로직을 컴포넌트쪽으로 옮겨서 수정하였습니다
- 주석처리 하였고, 기존 코드 적용시에는 문제가 없는 것을 확인하였습니다

- 마지막으로 src/pages/post/comment/index.tsx 컴포넌트에 기존 css 형식의 emotion/css 적용이 너무 어려워 styled 형식으로 적용하였습니다 이 부분은 제가 로직 마무리까지 담당하여 진행하도록 하겠습니다...!

2021-08-22 14:06 UTC, junh0328 commented on src/pages/post/style.tsx
> +      margin-bottom: 14px;
전체적으로 피그마를 그대로 적용하였는데, font-weight 부분이나 마진 패딩 값들이 정확히 없는 부분이 있어 온전히 똑같이 만들지는 못하겠네요 ㅋㅋㅋ ㅜㅜ 리뷰 부탁드립니다

2021-08-22 14:07 UTC, junh0328 commented on src/styles/global-styles.tsx
> +        /* max-width: 1024px; */
wide-pc 상황에서 화면단이 애매하게 스크롤 지는 현상때문에 max-width를 주석처리 하였습니다

2021-08-22 14:08 UTC, junh0328 commented on src/pages/_app.tsx
> +  /* padding: 0 20px; */
배경화면 적용시에, mainWrap의 패딩 사전 적용 때문에, 헤더가 100% 차지 않아 주석처리 하였습니다!

2021-08-23 08:17 UTC, leemember requested changes

2021-08-23 08:29 UTC, junh0328 commented on src/pages/_app.tsx
> +  /* overflow: scroll; */
혹시 그럼 이렇게 오른쪽에 스크롤 바가 무조건 생성되는 게 의도하신 게 맞나여?? 일단은 현주님 말씀대로 적용하였습니다!

## 스크롤바

<img width="477" alt="스크린샷 2021-08-23 오후 5 26 47" src="https://user-images.githubusercontent.com/54658162/130415782-f358888b-cf53-4ceb-98e0-ef6c51f96a77.png">

## 기존 현주님 코드 렌더링 화면

<img width="589" alt="스크린샷 2021-08-23 오후 5 27 09" src="https://user-images.githubusercontent.com/54658162/130415806-de1a91ed-4d66-4755-975a-6a8f1be96beb.png">

2021-08-23 08:31 UTC, junh0328 commented on src/pages/post/style.tsx
> +      margin-bottom: 14px;
말씀하신대로 변경 적용하였습니다!

2021-08-23 08:31 UTC, junh0328 commented on src/styles/global-styles.tsx
> +        /* max-width: 1024px; */
말씀하신대로 변경 적용하였습니다!

2021-08-23 08:31 UTC, junh0328 commented on src/pages/_app.tsx
> +  /* padding: 0 20px; */
말씀하신대로 변경 적용하였습니다!

2021-08-23 08:31 UTC, junh0328 commented on src/components/Common/FlatBox/index.tsx
> +    letter-spacing: -0.6000000238418579px;
너무 피그마에 나와있는 어트리뷰트를 복붙해버렸네요 ㅋㅋㅋ 수정했습니다

2021-08-23 08:31 UTC, junh0328 commented on src/components/Common/FlatBox/index.tsx
> +    font-size: 16px;
말씀하신대로 변경 적용하였습니다!

2021-08-23 08:32 UTC, junh0328 commented on src/components/Common/HashWrap/index.tsx
> +  font-size: ${Common.fontSize.fs14};
감삼다 ㅎㅎ

2021-08-23 08:32 UTC, junh0328 commented on src/components/Common/Header/BackOptional/index.tsx
> +    position: relative;
필히 숙지하여 다음 번에는 & 연산자의 남발을 줄이도록 하겠습니다... ㅋㅋㅋ 감사합니다!

2021-08-23 08:32 UTC, junh0328 commented on src/components/Common/Header/BackOptional/index.tsx
> +          </button>
말씀하신대로 변경 적용하였습니다!

2021-08-23 08:34 UTC, junh0328 commented on src/components/Common/Header/BackOptional/index.tsx
> +      <span>{title ? title : ''}</span>
잠깐 가려졌던 부분이라 추가적으로 변경하도록 하겠습니다!

2021-08-23 08:35 UTC, junh0328 commented on src/components/Common/Header/BackOptional/index.tsx
> +      <span>{title ? title : ''}</span>
[삼항 조건 연산자](https://pro-self-studier.tistory.com/37)

입니다!

함수형 프로그래밍에서는 if 문과 같은 조건문을 최소화하고, 코드의 부수효과를 줄이는 데 노력한다고 해서, 최대한 자제해보려고 노력하고 있습니다 ㅋㅋ

2021-08-23 11:22 UTC, junh0328 commented on src/components/Post/PostFooter/style.tsx
> +    &.active {
![스크린샷 2021-08-23 오후 8 22 25](https://user-images.githubusercontent.com/54658162/130439328-5323ac40-2796-47a4-b280-dad85b46908c.png)

svg는 이쪽 마진 right 관련인데 필요 없을까요?

2021-08-23 11:23 UTC, junh0328 commented on src/components/Post/PostFooter/style.tsx
> +export const footerNavWrap = css`
적용 및 삭제하였습니다!

2021-08-23 11:26 UTC, junh0328 commented on src/components/Post/PostFooter/style.tsx
> +  & button {
```css
export const footerNavWrap = css`
  margin: 0 auto;
  width: 100%;
  display: flex;
  height: 50px;
  align-items: center;
  justify-content: space-around;

  li {
    text-align: center;
    align-items: center;

    a {
      display: flex;
      align-items: center;
    }
    /*  */
    svg {
      margin-right: 9px;
    }
    span {
      font-size: 18px;
    }
  }
  p {
    text-align: center;
    font-size: 1.2rem;
    color: #b6b2b0;
    font-weight: 500;
    line-height: 1.5rem;
    margin-top: 0.5em;
  }

  & button {
    background-color: #ff6e35;
    border-radius: 16px;
    width: 59.2%;
    padding: 16px 0;

    color: white;
    text-align: center;

    font-family: 'Spoqa Han Sans Neo';
    font-size: 18px;
    font-style: normal;
    font-weight: 500;
    line-height: 20px;
    letter-spacing: -0.30000001192092896px;
  }
`
```

현재 display: flex에 justify-content: space-around; 로 작업을 해서 그런지, 59.2%로 두면 어제 페어코딩 때 봤던 것처럼 찌그러지는 데 어떻게 할까욥?

2021-08-23 11:29 UTC, junh0328 commented on src/components/Post/PostFooter/style.tsx
> +  }
적용하였습니다!

2021-08-25 04:53 UTC, leemember approved these changes
수고하샸습니다!!!

2021-08-25 05:00 UTC, merged