[WSC-021] 회원가입 (1)
MIC-TEAM/wellseecoding-front pull request #25
Opened 2021-09-26 15:30 UTC by leemember

# 📄 이슈 내용 #21 

### 회원가입 과정 작업
 ![](https://images.velog.io/images/leemember/post/d5696eb4-6413-4dd1-b5e7-b1980d0ab775/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202021-09-13%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%206.09.52.png)

## 📝 상세 내용
- 회원가입 과정 중 redux-saga로 비동기 통신하기 전, useCallback 이용하여 axios 통신 작업하기

## ✔  작업 여부 체크리스트 (페이지 이동 순서)

## 회원가입 페이지 
> 🗂 (./sign_up)
- [x]  유효성 검사 완료 되었나요 ? 
- 이메일 형식대로 작성하기.
- 비밀번호는 특수문자 + 숫자 + 영문 포함 8글자 이상으로 입력하기
- 비밀번호 확인 시 처음 입력했던 비밀번호와 동일하도록
- [x]  완벽한 조건으로 폼형식을 다 채웠을 경우 다음 버튼 disabled 구현
- [x]  axios 데이터 통신

## 프로필 시작 페이지 
> 🗂 (./sign_up/profile_start)
- [x]  나중에 할래요 버튼 클릭 구현
- 바로 홈 화면으로 이동되도록
- [x]  네~ 버튼 클릭 구현
- 어떤 일을 하고계세요 ? 페이지로 이동
- [x]  axios 데이터 통신

## 어떤 일을 하고계세요 ? 페이지
> 🗂 (./sign_up/something_job)
- [x]  학생, 취준생, 직장인 중 한 가지 선택될 시 다음 버튼 disabled 구현
- [x]  axios 데이터 통신

## 자기소개 해주세요! 페이지 
> 🗂 (./sign_up/self_introduction)
- [x]   간단하게 자기 소개해주세요!
- 한 글자 이상 입력해야됨
- [x]   기술 스택을 해시태그로 입력해주세요!
- 한 글자 이상 입력해야됨 (나중에 준희님이 작업하신 해시태그 블록 끌어다쓰기)
- [x]  폼형식을 다 채웠을 경우 다음 버튼 disabled 구현
- [x]  axios 데이터 통신

## 학교 정보를 적어주세요! 페이지 
> 🗂 (./sign_up/school)
- [x] 학위 입력폼
- 한 글자 이상 입력해야됨
- [x]  전공 입력폼
- 한 글자 이상 입력해야됨
- [x]  재학 및 졸업 여부 input type="radio" 한 가지라도 선택될 시 다음 버튼 disabled 구현
- [x]  나중에 쓸게요~ 버튼 클릭 시 경력 정보를 적어주세요! 페이지로 이동
- [x]  axios 데이터 통신

## 경력 정보를 적어주세요! 페이지 
> 🗂 (./sign_up/experience)
- [x]  역할 입력폼
- 한 글자 이상 입력해야됨
- [x]  기술스택 입력폼
- 한 글자 이상 입력해야됨
- [x]  경력년도 입력폼
- 한 글자 이상 입력해야됨
- [x]  역할, 기술스택, 경력년도 입력이 완성 된 한 컴포넌트 박스만 완성되어도 다음 버튼 disabled 구현
- [x]  나중에 쓸게요~ 버튼 클릭 시 포트폴리오를 올려주세요! 페이지로 이동
- [x]  axios 데이터 통신

## 포트폴리오를 적어주세요! 페이지 
> 🗂 (./sign_up/portfolio)
- [x] 프로젝트 이름 입력폼
- 한 글자 이상 입력해야됨
- [x]  링크 입력폼
- 한 글자 이상 입력해야됨
- [x]  설명 입력폼
- 한 글자 이상 입력해야됨
- [x]  프로젝트명, 링크, 설명 입력이 완성 된 한 컴포넌트 박스만 완성되어도 다음 버튼 disabled 구현
- [x]  나중에 쓸게요~ 버튼 클릭 시 프로필 사진 올려주세요! 페이지로 이동
- [x]  axios 데이터 통신

## 프로필을 모두 완성했어요 페이지 
> 🗂 (./sign_up/completion)
- [x]  시작하기 버튼 클릭 시 메인페이지로 이동 (./home)

## 비밀번호 찾기
> 🗂 (./sign_in/reset_password)
- [x]  유효성 검사
- [x]  axios 데이터 통신

## 이메일 로그인
> 🗂 (./sign_in/email_start)
- [x]  유효성 검사

2021-09-27 04:53 UTC, junh0328 requested changes
전체적으로 많이 고쳐야할 것 같습니다

onSubmit 함수 내부에서 axios로 HTTP 요청을 보내기 전에 데이터를 전달할 준비가 되었는지 확인하는 게 우선이 될 것 같습니다

📌 핀 표시 되어있는 부분에 공통적으로 onSubmit 관련 문제에 대해 적어놓았습니다 

천천히 확인해보시고 하다가 모르시는 거 생기시면 말씀해주세요

2021-09-27 04:53 UTC, junh0328 commented on src/pages/sign_up/index.tsx
> +  }, [])
해당 부분 코드가 변경이 필요해 보입니다!

```tsx
const onSubmit = useCallback(
    async (e: React.FormEvent<HTMLFormElement>) => {
      e.preventDefault()

      try {
        await axios
          .post(REGISTER_USERS_URL, {
            username: name,
            password: password,
            email: email,
          })
          .then((res) => {
            console.log('response:', res)
            if (res.status === 200) {
              router.push('/sign_up/profile_start')
            }
          })
      } catch (err) {
        console.error(err)
      }
    },
    [email, name, password, router]
  )
```

데이터를 보내기 전에 router.push를 한다면 axios 요청이 일어나기 전에 라우팅될 수 있습니다.
그리고 onSubmit과 같이 함수 내부에서 데이터를 유지하려면 callback과 함께 클린업 함수 자리에 해당되는 state를 추가하셔야 합니다!

2021-09-27 04:53 UTC, junh0328 commented on src/pages/sign_up/index.tsx
> +  }, [])
기존 현주님 코드 상에서는 네트워크 탭에서 확인해보시면 아시겠지만, 제대로 서버로 요청을 보내지 못하는 상태였습니다!

- [400 Bad Request 🔥](https://developer.mozilla.org/ko/docs/Web/HTTP/Status/400)

2021-09-27 04:53 UTC, junh0328 commented on src/pages/sign_up/portfolio/index.tsx
> +  }, [])
<img width="1193" alt="스크린샷 2021-09-27 오후 1 20 04" src="https://user-images.githubusercontent.com/54658162/134844944-8814b9b1-c42c-4f77-aa99-9d54bb80a79c.png">

포트폴리오 페이지에서 다음 버튼 클릭시에, 네트워크 탭에서 put 요청에 대해서 404 에러가 뜨는 것으로 보입니다

2021-09-27 04:53 UTC, junh0328 commented on src/pages/sign_up/portfolio/index.tsx
> +  }, [])
위에 남긴 리뷰처럼 
```js
router.push('/sign_up/profile_upload')
```
는 axios 요청 밑에 있어야 할 것 같고, axios를 보내시기 전에 alert로 데이터가 정확히 넘어가는지 확인을 하신지 모르겠네요

2021-09-27 04:53 UTC, junh0328 commented on src/pages/sign_up/portfolio/index.tsx
> +  }, [])
<img width="1194" alt="스크린샷 2021-09-27 오후 1 24 17" src="https://user-images.githubusercontent.com/54658162/134845185-052131e2-daaf-4de9-9da4-ffa7f95c109d.png">

```js
const onSubmit = useCallback(async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    alert(`name: ${project},<br/>
    link: ${link},<br/>
    description: ${desc},`)
  }, [])
```
지금 현주님 코드에서 router 부분하고 axios 부분을 제외하고 alert로 상태(state)를 잘 넘겨주고 있는지 확인해봤는데 아무것도 넘어오지 않습니다.

2021-09-27 04:53 UTC, junh0328 commented on src/pages/sign_up/portfolio/index.tsx
> +  }, [])
<img width="695" alt="스크린샷 2021-09-27 오후 1 25 54" src="https://user-images.githubusercontent.com/54658162/134845301-2ad6745c-fa73-4d88-a2db-6a8e8872278b.png">

클린업 함수를 클릭해 보시면 useCallback 사용 시 상태를 감지할 변수(state)들이 빠져있어서 데이터가 넘어오지 않는 것으로 보입니다 

위에 src/pages/sign_up/index.tsx 에 남긴 코드처럼 useCallback에 해당 변수를 넣어주시고, axios 요청 성공시에 다음 페이지로 넘어갈 수 있도록 변경하셔야 될 것 같습니다.

2021-09-27 04:53 UTC, junh0328 commented on src/pages/sign_up/portfolio/index.tsx
> +  }, [])
```tsx
 const onChangeProject = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    setProject(e.target.value)

    if (e.target.value.length) {
      console.log('length:', e.target.value.length)
      setIsProject(true)
    } else {
      setIsProject(false)
    }
  }, [])
```

위 코드를 적용해 보시면 아시겠지만, e.target.value.length 라는 것 자체가 truthy한 값이라 1로 적용됩니다

if(...length > 0) 은

if(...length) 와 같습니다

불필요한 console.log도 제거하는 편이 좋겠네요!

2021-09-27 04:53 UTC, junh0328 commented on src/pages/sign_up/profile_start/index.tsx
> +  }
'next/router' 라이브러리에서 제공하는 useRouter의 메소드 push가 애초에 리렌더링이 되지 않기 때문에 e.preventDefault()를 사용하지 않으셔도 됩니다. 용도에도 맞지 않는 것 같습니다..!

```js
const NextHome = () => {
    router.push('/home')
  }

  const NextPage = () => {
    router.push('/sign_up/something_job')
  }
```

https://user-images.githubusercontent.com/54658162/134846118-8420300f-f280-4ace-afa3-6366233e9169.mov

리 렌더링이 될 경우에는 탭이 새로고침 되면서, 빈 네트워크 탭에서 새롭게 불러오게 되는데 router.push 메서드 자체가 리렌더링을 시키지 않는 것으로 보입니다

2021-09-27 04:53 UTC, junh0328 commented on src/pages/sign_up/school/index.tsx
> +  }, [])
위 코드에 리뷰했던 것처럼 callback의 클린업 함수에는 보내야할 state 값을 넣어주시고, router.push는 해당 데이터가 정상적으로 보내졌을 때 then에서 처리하는 편이 나을 것 같습니다!

2021-09-27 04:53 UTC, junh0328 commented on src/pages/sign_up/school/index.tsx
> +  }, [])
** 대학 / **대학교 라는 가정하에 최소 4글자정도도 괜찮을 것 같습니다

2021-09-27 04:53 UTC, junh0328 commented on src/pages/sign_up/school/index.tsx
> +  }, [])
**학/ ** 학과 라고 가정했을 때 length가 3글자 정도 되도 괜찮을 것 같습니다

2021-09-27 04:53 UTC, junh0328 commented on src/pages/sign_up/school/index.tsx
> +  }, [])
https://user-images.githubusercontent.com/54658162/134846628-d9f25499-c936-4caf-be3a-5f072596e484.mov

재학중 / 졸업 버튼만 클릭해도 다음버튼이 활성화가 되는데, 3개의 state를 모두 감지해서 true 인 상황에 다음버튼을 활성화해야 할 것 같습니다

2021-09-27 04:53 UTC, junh0328 commented on src/pages/sign_up/self_introduction/index.tsx
> +  }, [])
이쪽은 원래 다음 버튼 눌렀을 때 axios 요청을 2개나 보내게 되어있나요?

2021-09-27 04:53 UTC, junh0328 commented on src/reducers/users/index.tsx
> +}
인터페이스 명을 타입과 관계없이 그대로 쓰실 경우에 사가 코드에서 SIGNUP 관련이 아닌 FETCHING POST 쪽 인터페이스를 타입으로 지정할 수 있어서 관련 이름으로 변경해야 할 것 같습니다

2021-09-27 04:53 UTC, junh0328 commented on src/reducers/users/index.tsx
> +  | ReturnType<typeof fetchingPostsFailure>
위에 내용과 같습니다

2021-09-27 04:53 UTC, junh0328 commented on src/pages/sign_up/experience/index.tsx
> +  }, [])
onSubmit 폼 관련 로직 수정 부탁드릴게요

2021-09-27 04:53 UTC, junh0328 commented on src/pages/sign_in/reset_password/index.tsx
> +  }, [])
onSubmit 폼 관련 로직 수정 부탁드릴게요

2021-09-27 04:53 UTC, junh0328 commented on src/pages/sign_in/email_start/index.tsx
> +  )
이쪽 코드에는 useCallback 클린업으로 state가 제대로 들어가있네요!

2021-09-27 16:10 UTC, leemember commented on src/pages/sign_in/reset_password/index.tsx
> +  }, [])
앗 틀만 냅두고 추후에 API 완성되면
교체해 넣으려고 했는데 비워두도록 하겠습니다!

2021-09-27 16:17 UTC, leemember commented on src/pages/sign_up/index.tsx
> +  }, [])
![스크린샷 2021-09-28 오전 1 15 28](https://user-images.githubusercontent.com/71499150/134946358-03a42705-c95d-44c2-a909-8b33d1c3d26f.png)

감사합니다!! 피드백 주신 코드로 수정해서 넘어가는 것 까지 확인했습니다!
다른 작업들도 []에 state 추가하도록 하겠습니다 ㅎㅎ..!

2021-09-27 16:53 UTC, leemember commented on src/pages/sign_up/portfolio/index.tsx
> +  }, [])
## 알려주신대로

```
  const onSubmit = useCallback(
    async (e: React.FormEvent<HTMLFormElement>) => {
      e.preventDefault()
      try {
        await axios
          .post(REGISTER_LINK_URL, {
            name: project,
            link: link,
            description: desc,
          })
          .then((res) => {
            console.log('response:', res)
            if (res.status === 200) {
              router.push('/sign_up/profile_upload')
            }
          })
      } catch (err) {
        console.error(err)
      }
    },
    [project, link, desc, router]
  )
```

## 이렇게 상태를 넣은 거랑

![스크린샷 2021-09-28 오전 1 34 33](https://user-images.githubusercontent.com/71499150/134951388-ed714c82-e199-4e5c-b1c3-7865f738bce5.png)


## 안넣은거랑

![스크린샷 2021-09-28 오전 1 38 57](https://user-images.githubusercontent.com/71499150/134951443-9765e559-57ce-4d7d-9d62-dd6c29d07c32.png)


확인해봤는데 신기하네요 ㅎ_ㅎ
근데 config 데이터는 잘 받아와지는데
첫 줄에 데이터 쪽에는 html 요소들이 넘어와지는데
이게 맞는 걸까요 ? 😲  🥵

2021-09-27 17:26 UTC, leemember commented on src/pages/sign_up/portfolio/index.tsx
> +  }, [])
오.... 천재....🤭 첨 알았네요 감사합니다 !!!!
불필요한 console.log도 제거했습니당!

2021-09-27 17:27 UTC, leemember commented on src/pages/sign_up/profile_start/index.tsx
> +  }
그러네요 맞습니다 ㅜㅜ! 감사합니다!!

2021-09-27 17:40 UTC, leemember commented on src/pages/sign_up/self_introduction/index.tsx
> +  }, [])
넹 둘 다 api 주소가 달라서요 ㅜ..
근데 제가 봐도 저 부분 비동기 코드가 이상한 것 같아서

https://velopert.com/1552

위 링크에 아래 코드 참고해서

```
axios.get('/user?id=velopert')
    .then( response => { console.log(response); } ) // SUCCESS
    .catch( response => { console.log(response); } ); // ERROR

axios.get('/user', {
        params: { id: 'velopert' }
    })
    .then( response => { console.log(response) } );
    .catch( response => { console.log(response) } );

// catch 는 생략 될 수 있습니다.
```

-------------------

```

  const onSubmit = useCallback(
    async (e: React.FormEvent<HTMLFormElement>) => {
      e.preventDefault()
      alert(`자기소개: ${aboutMe}, 기술스택: ${skill}`)
      try {
        await axios.put(REGISTER_ABOUT_ME_URL, {
          aboutMe: aboutMe,
        })
        axios
          .put(REGISTER_WORK_URL, {
            works: [
              {
                technology: skill,
              },
            ],
          })
          .then((res) => {
            console.log(res.data)
            if (res.status === 200) {
              router.push('/sign_up/school')
            }
          })
      } catch (err) {
        console.error(err)
      }
    },
    [aboutMe, skill]
  )

```

이렇게 수정해봤습니다! 😶

2021-09-27 17:45 UTC, leemember commented on src/pages/sign_up/experience/index.tsx
> +  }, [])
옛썰 🙌

2021-09-27 17:47 UTC, leemember commented on src/pages/sign_in/email_start/index.tsx
> +  )
ㅎㅎ..준희님꺼 코드보고 모양새 흉내내보려고 넣어봤는데
왜 쓰는지는 몰랐는데 알게돼서 좋습니다 감사합니다!!!

2021-09-27 17:56 UTC, leemember commented on src/reducers/users/index.tsx
> +}
넵 !!

2021-09-27 23:16 UTC, junh0328 commented on src/pages/sign_up/portfolio/index.tsx
> +  }, [])
404는 서버에서 열어둔 라우팅 주소와 일치하지 않을 때 발생하는 문제입니다!

아무래도 포스트맨으로 보내보시고 거기서도 안돼면 일섭님이랑 상의해보는 편이 좋겠네요!

2021-09-27 23:19 UTC, junh0328 commented on src/pages/sign_up/portfolio/index.tsx
> +  }, [])
usecallback에서 의존성 부분은 useState로 관리하는 state가 리렌더링될 때마다 값을 잃지 않게 유지해주는 기능이라 links는 따로 넣지 않으셔도 될 것 같습니다 

지금 정상적으로 보내지는 가 아닌가욥?

2021-09-28 16:41 UTC, leemember commented on src/pages/sign_up/portfolio/index.tsx
> +  }, [])
넵..! api 해당주소로 정확하게 넣었는데

```
// 포트폴리오
export const REGISTER_LINK_URL = '/api/v1/users/profile/links'
```

이상하게 login 으로 자동 리다이렉팅이 되네염 😧


![스크린샷 2021-09-29 오전 1 01 20](https://user-images.githubusercontent.com/71499150/135123765-72def2f7-07fc-46ff-94ab-b15e04efb540.png)
![스크린샷 2021-09-29 오전 12 59 41](https://user-images.githubusercontent.com/71499150/135123693-e43a76f9-0952-40eb-b767-c77ab929d4d1.png)

2021-09-29 05:13 UTC, junh0328 approved these changes
잘 적용되었네요 고생하셨습니다 ~

2021-09-29 05:14 UTC, merged