[wsc-003] add : 공통 파일 세팅작업
MIC-TEAM/wellseecoding-front pull request #3
Opened 2021-07-31 09:59 UTC by leemember

- max-width 값을 아이패드 기준으로, min-width 값을 모바일 사이즈로해서 레이아웃 세팅완료 했습니다.
(미디어쿼리 작업 필요성이 없다 느껴 처음부터 최대값과 최소값을 정해서 레이아웃 설정 했습니다.) 
📍 프론트 작업하실 때 개발자 도구에서 디바이스는 375px 값으로 맞춰서 작업하시면 될 것 같습니다.

![스크린샷 2021-07-31 오후 6 58 25](https://user-images.githubusercontent.com/71499150/127736302-36a6a5dd-31c9-4b52-be7b-d839734fac77.png)

- Footer Menu 작업
- 공통 Header 작업 (뒤로가기 버튼)
- 자주 사용하는 포인트 컬러 (글로벌 스타일이라 css={ } 로 바로 불러와서 사용하시면 됩니다.)
- Button 태그 초기화 설정

코드리뷰 부탁드립니다 감사합니다 :)

2021-07-31 11:27 UTC, junh0328 requested changes

2021-07-31 11:27 UTC, junh0328 commented on src/styles/colors.tsx
> +export const orange = css`
해당 변수는 예를 들어, 위에 만든 ProfileStart에 `color: orange`와 같이 사용하는 건가요..? 
처음 써보는 방식이라 예시로 같이 넣어주시거나 설명 달아주시면 감사하겠습니다!

2021-07-31 11:56 UTC, junh0328 commented on src/components/Fnb/index.tsx
> +const Fnb = () => {
컴포넌트명을 Fnb로 하신 특별한 이유가 있을까요?
Layout이나 AppLayout 뭐 이런 것도 많이 쓰긴 하더라구요..!

2021-07-31 12:12 UTC, leemember commented on src/components/Fnb/index.tsx
> +const Fnb = () => {
![스크린샷 2021-07-31 오후 9 10 25](https://user-images.githubusercontent.com/71499150/127739451-71547729-15d4-4cfa-8048-4f41d444f317.png)

이거 본따서 푸터에 있는 네비바라 Fnb라고 지었는데 모두 알아보기 좋게 FooterMenu라고 할까욥 ?

2021-07-31 12:24 UTC, junh0328 commented on src/components/Fnb/index.tsx
> +const Fnb = () => {
아 제가 무지해서 잘 몰랐네요...!
아닙니다 앞으로는 저런 방식 사용해서 만들어야 겠네요 ㅋㅋㅋㅋ ㅜ 좋은 정보 공유 감사합니다

2021-07-31 12:31 UTC, junh0328 commented on src/components/Fnb/index.tsx
> +const Fnb = () => {
아 또 자세히 보니 웹표준은 아니군요 ㅋㅋㅋ FooterMenu 정도면 충분할 것 같습니다!!

2021-07-31 12:48 UTC, leemember reviewed
준희님 말 반영해서 Fnb 약자 사용하는 것보다 풀네임으로 다들 알아보기 좋게 하는 것이 더 좋을 것 같아서 컴포넌트 파일명 수정했습니다!
그리고 colors도 컬러들을 배열로 넣어서 다시 수정했습니다!

2021-07-31 12:48 UTC, leemember commented on src/styles/colors.tsx
> +export const orange = css`
![스크린샷 2021-07-31 오후 9 43 32](https://user-images.githubusercontent.com/71499150/127740266-7884b630-e18f-482f-88cb-fe4fe224af3b.png)

이건 저도 Emotion.js 예제보고 다시 color 코드들을 배열로 정리해 놓았는데용.
사용하고자 하는 컬러코드를 `import { colors } from '../styles/colors'`
이렇게 임포트 시키신 다음에  `<h1 css={colors.orange}>👋 mic-team Boilerplate</h1>`
이런식으로 사용하시면 됩니다!

또 편하게 질문해주세요! 감사합니다!

2021-07-31 12:51 UTC, junh0328 commented
예를 들어 위에 현주님이 올려주신 container 변수 내부의 이모션 css 적용에 있어서도
`
const container = css
color: colors.orange
`
와 같이 접근할 수 있는건가요??

2021-07-31 12:53 UTC, junh0328 commented on src/styles/colors.tsx
> +export const orange = css`
예를 들어 위에 현주님이 올려주신 container 변수 내부의 이모션 css 적용에 있어서도
```js
const container = css`
color: colors.orange
`
```
와 같이 접근할 수 있는건가요??

2021-07-31 13:41 UTC, devho813 commented
feature 브랜치는 develop 생성 후 develop 브랜치로 머지 해야 합니다!

2021-07-31 15:17 UTC, leemember commented
헉...... 담부터 develop에서 브런치 따도록 하겠습니다..!!!!! 몰랐네요 죄송합니다 ㅜㅠ

2021-08-01 05:29 UTC, junh0328 commented on src/pages/_app.tsx
> +import '../styles/common'
common 디렉토리를 `_app.tsx`에 적용해야 하위 디렉토리에서 사용할 수 있는 건가요?

2021-08-01 05:31 UTC, leemember commented on src/pages/_app.tsx
> +import '../styles/common'
앗 제거하겠습니다 !! 감사합니다!!

2021-08-01 05:32 UTC, junh0328 reviewed
어차피 커밋 추가하면 Approve 다시 해야 해서 변경한다음에 바로 Approve 하겠습니다!

2021-08-01 05:32 UTC, junh0328 commented on src/pages/index.tsx
> +    font-size: ${Common.fontSize.fs22};
이렇게 사용하는군요!!
확인했습니다 ㅎㅎ

2021-08-01 05:34 UTC, leemember commented on src/pages/index.tsx
> +    font-size: ${Common.fontSize.fs22};
넵 !! 감사합니당 :)
common 스타일 가이드는 위키에다가 정리해뒀습니당!
확인 부탁드립니다!

2021-08-01 05:36 UTC, junh0328 commented on src/pages/index.tsx
> +    font-size: ${Common.fontSize.fs22};
아 네네 위키는 슬랙에 스레드에 남겨주셔서 읽어보았습니다!! 
정리 감사합니다

2021-08-01 05:37 UTC, junh0328 submitted a review, later dismissed

2021-08-01 05:41 UTC, devho813 requested changes

2021-08-01 05:43 UTC, leemember commented on src/pages/index.tsx
> +import Header from '../components/Header/back'
넵!! 반영하겠습니다!

2021-08-01 05:44 UTC, leemember commented on src/pages/index.tsx
> +import Fnb from '../components/FooterMenu'
HeaderBack 으로 반영하겠습니다!

2021-08-01 05:45 UTC, leemember commented on src/pages/login/index.tsx
> +import { css } from '@emotion/react'
넵~~! 👍🏻

2021-08-01 06:16 UTC, devho813 approved these changes

2021-08-01 06:39 UTC, junh0328 approved these changes

2021-08-01 12:40 UTC, Roharui approved these changes
Global 태그는 처음 알았네요!

2021-08-01 12:40 UTC, Roharui commented on src/styles/common.tsx
> +}
이 css 목록들은 컴포넌트를 디자인할때 가져다 쓰는 거죠?

2021-08-01 12:41 UTC, leemember commented on src/styles/common.tsx
> +}
맞습니당 위키에다가 적용법이랑 설명해놨어요!!

2021-08-01 12:42 UTC, merged