[wsc-004] 공통 컴포넌트 및 페이지 작업
MIC-TEAM/wellseecoding-front pull request #5
Opened 2021-08-07 18:36 UTC by leemember

## 📍 [wsc-004] 공통 컴포넌트 및 페이지 작업

### 공통 컴포넌트 생성
1. footer 버전 버튼 (클래스 네이밍에 따라 one버튼 two버튼 사용가능)
2. font-size 40px 인 bitTitle
3. 자주 사용하는 일반 Title 
4. 공통 텍스트 필드 Input 폼태그 (input type에 따라 사용가능)
5. 비밀번호용 Input 폼태그
⭐️   Material UI 폼태그 커스터마이징 (글로벌 스타일에 적용)

### 페이지 작업 
- 마크업만 해놓은 상태입니다.
1. Auth 로그인 페이지
2. 이메일 로그인 페이지
3. 비밀번호 찾기 - 이메일 인증번호
4. 비밀번호 찾기 - 비밀번호 재설정
5. 회원가입 - 프로필 만들기 시작
6. 회원가입 - 프로필 사진 업로드 (레이아웃만 갖춰논 상태)
7. 회원가입 - 프로필 완성 및 웰시 바로 시작하기

### 설치한 패키지들
 
```
"@material-ui/core": "^4.12.3",
"@material-ui/icons": "^4.11.2",
"@material-ui/styles": "^4.11.4",
```

늘어지는 일정이 싫어서 빠른 작업을 위해 트랠로에 없던 작업들도 추가로 작업했습니다.
디자인 픽스 되는대로 컴포넌트 및 페이지 생성 하도록 하겠습니다.

코드 리뷰 부탁드립니다 감사합니다 :)

2021-08-08 03:32 UTC, junh0328 commented
이거 브랜치 작업이 어디서 시작됐는지 찬호님 커밋이 위에 달려있는데, 맞는건가요?

2021-08-08 03:51 UTC, junh0328 requested changes

2021-08-08 03:51 UTC, junh0328 commented on src/components/Common/FootButton/index.tsx
> +        background: #ff6e35;
몇몇 색깔 속성은
```
background: ${Common.colors.gray04};
```
와 같이 Common에서 불러오는 작업이 되어있는데, 몇개는 그냥 불러오네요!!
의도하신 부분인가요?

2021-08-08 03:51 UTC, junh0328 commented on src/components/Common/FootButton/index.tsx
> +        <button type="button" className={className1}>
해당 컴포넌트가 재 사용성을 위해서 className을 props로 전달받아서 만드신 것 같은데, 
저도 emotion css를 사용해본 적이 없어서 쉽지 않네요 ㅋㅋㅋㅋ ㅜㅜ
예를 들어 emotion styled와 같이 props의 value를 css로 전달하여 조건 연산자를 통해 나열하는 방법은 없나요?

```js
<MainContent key={data.id} complete={data.completed}>
```

```js
import styled from '@emotion/styled'

interface StyledDivProps {
  complete: boolean
}

export const MainContent = styled.div<StyledDivProps>`
  border: 1px solid black;
  margin: 20px 0;
  padding: 20px;
  background-color: ${(props) => props.complete === false && 'salmon'};
  & p {
    font-weight: bolder;
  }
`
```

이번에는 emotion css를 사용하기로 했기 때문에 저도 현주님이 작업하신 코드를 바탕으로 공부해보겠습니다.

2021-08-08 03:51 UTC, junh0328 commented on src/components/Common/Header/back.tsx
> +    <header css={backHeader}>
div 태그를 header라는 시멘틱으로 변경하신 이유가 있나요?

2021-08-08 03:51 UTC, junh0328 commented on src/pages/_app.tsx
> +      <main css={mainWrap}>
div 태그가 아닌 main 이라는 시멘틱을 사용하신 이유가 있나요?

2021-08-08 03:51 UTC, junh0328 commented on src/pages/login/auth_start/index.tsx
> +const authLoginTitleWrap = css`
공통되는 부분인데, css를 따로 분리하지 않고 한 파일에 작성하는 것이 더 낫나요? 
저는 스타일드 컴포넌트 형의 작업 방식 때문인지, 무조건 styled.tsx를 만들어서 import 하는 것을 선호해서 여쭤봅니다..!

2021-08-08 07:27 UTC, Roharui approved these changes

2021-08-08 07:27 UTC, Roharui commented on src/components/Common/PasswordField/index.tsx
> +  const [values, setValues] = React.useState<State>({
`useState`의 경우는 React를 생략해도 되지 않을까요?

2021-08-08 07:27 UTC, Roharui commented on src/components/Common/TextField/index.tsx
> +type Props = {
이 인자는 `interface`가 아닌 `type`으로 둔 이유가 있나요?

2021-08-08 07:27 UTC, Roharui commented on tsconfig.json
> +  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "src/components/Common/BigTitle"]
이렇게 따로 `BigTitle`을 추가해 두신건 어떤 의미인가요?

2021-08-08 15:00 UTC, devho813 commented on src/components/AuthLogin/index.tsx
> +      <button type="button" className="kakao">
.active, .checked 같은 특정 상황일 때 동적으로 스타일을 주기 위한 className 설정이 아니면
emotion로 통일하여 일관성 있게 구현하는 것이 좋을 것 같습니다~

2021-08-08 15:24 UTC, devho813 commented
오잉 해당 브랜치 wsc-002에서 따셨나요?
제 테스트 커밋 이력이 포함되어있네요 😲

2021-08-09 07:34 UTC, leemember commented on src/components/Common/FootButton/index.tsx
> +        background: #ff6e35;
이게 폰트사이즈는 잘 적용되는데 컬러는.. 몇개는 잘 안먹히더라구요 ㅠㅠ
그래서 컬러 적용 안된 것들은 바로 헥스코드로 적용했습니다!

2021-08-09 07:35 UTC, leemember commented on src/components/Common/FootButton/index.tsx
> +        <button type="button" className={className1}>
아마 있을건데 저도 한 번 연구해보고 알려드릴게요 ㅎㅎ!

2021-08-09 07:36 UTC, leemember commented on src/components/Common/Header/back.tsx
> +    <header css={backHeader}>
back 버튼이 헤더에 위치해 있어서 의미있게 header로 마크업했습니다!

2021-08-09 07:41 UTC, leemember commented on src/pages/_app.tsx
> +      <main css={mainWrap}>
앗 감사합니당 마크업 태그를 잘못 선택한 듯 하네요 ! div로 다시 바꾸겠습니당.
의미있는 마크업을 위해 참고자료도 같이 첨부하겠습니다 🙃

참고자료 : https://www.zerocho.com/category/HTML&DOM/post/5821b15f577d375e5c73bbc5

2021-08-09 07:43 UTC, leemember commented on src/pages/login/auth_start/index.tsx
> +const authLoginTitleWrap = css`
아 보고나니 그렇네요 ! styled.tsx 파일 따로 분리하여 공통으로 사용하겠습니다!! 👍🏻

2021-08-09 07:44 UTC, leemember commented on src/components/Common/PasswordField/index.tsx
> +  const [values, setValues] = React.useState<State>({
import React, { useState } from 'react' 이렇게 추가하고 저 부분은 생략하여 수정하겠습니당 감사합니다 ! :)

2021-08-09 07:45 UTC, leemember commented on src/components/Common/TextField/index.tsx
> +type Props = {
바로 export 시키는 것은 type으로 하자고 저희끼리 단톡방에서 약속했던 내용이라 저렇게 반영 했습니다!

2021-08-09 07:45 UTC, leemember commented on tsconfig.json
> +  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "src/components/Common/BigTitle"]
이건 왜 이렇게 추가 됐는지.. 모르곘네욥..

2021-08-09 07:49 UTC, leemember commented on src/components/AuthLogin/index.tsx
> +      <button type="button" className="kakao">
넵 알겠습니당 ! 반영하겠습니다! 😃

2021-08-09 07:49 UTC, leemember commented
아니요 ! developer 브런치에서 땃습니다!

2021-08-09 08:42 UTC, leemember commented
모두덜 코드리뷰 감사합니다 ! 모두 반영해서 푸시했습니다 😄

2021-08-09 14:32 UTC, devho813 commented
현주님 해당 PR develop 브랜치로 머지 하셔야 할 것 같습니다~

2021-08-09 19:48 UTC, leemember commented
변경했습니다 ! 승인해주시면 머지하도록 하겠습니다
리팩토링 작업 감사합니다 :)

2021-08-10 01:31 UTC, devho813 approved these changes

2021-08-10 01:31 UTC, devho813 commented
리뷰 완료했습니다 고생하셨어요!

2021-08-10 03:49 UTC, junh0328 approved these changes
늦은 시간까지 작업하셨군요.. 
변경사항은 모두 확인하였습니다 수고하셨어요!!

2021-08-10 05:26 UTC, merged